
<head>
    <style>
        #file{
    color: #0c7cd5;
    padding:5px; 
    background-color: #f9ffe5;
}
#img{ 
    width: 30px;
    border: none; 
    height:30px;
    margin-left: -20px;
    margin-bottom: 91px;
}

.abcd{
    text-align: center;
}

.abcd img{
    height:100px;
    width:100px;
    padding: 5px;
    border: 1px solid rgb(150, 222, 189);
}


    </style>
    
    <script   src="https://code.jquery.com/jquery-1.12.3.min.js" ></script>
    <script type="text/javascript">
    
    var abc = 0; //Declaring and defining global increement variable

$(document).ready(function() {
    var click =0;
//To add new input file field dynamically, on click of "Add More Files" button below function will be executed
    $('#add_more').click(function() {
        click += 1;
        if(click < 5)
        {
        $(this).before($("<div/>", {id: 'filediv'}).fadeIn('slow').append(
                $("<input/>", {name: 'file[]', type: 'file', id: 'file'}),        
                $("<br/>")
                ));
        }
    });
    //following function will executes on change event of file input to select different file	
//$('body').on('change', '#file', function(){
//            if (this.files && this.files[0]) {
//                 abc += 1; //increementing global variable by 1
//				
//				var z = abc - 1;
//                var x = $(this).parent().find('#previewimg' + z).remove();
//                $(this).before("<div id='abcd"+ abc +"' class='abcd'><img id='previewimg" + abc + "' src=''/></div>");
//               
//			    var reader = new FileReader();
//                reader.onload = imageIsLoaded;
//                reader.readAsDataURL(this.files[0]);
//               
//			    $(this).hide();
//                $("#abcd"+ abc).append($("<img/>", {id: 'img', src: 'images/x.png', alt: 'delete'}).click(function() {
//                $(this).parent().parent().remove();
//                }));
//            }
//        });
//
////To preview image     
//    function imageIsLoaded(e) {
//        $('#previewimg' + abc).attr('src', e.target.result);
//    };

});
    
    </script>
        
</head>
<div class="container">
    
    <br><br>
    <legend> Add Product Details </legend>
    <br><br>
    
    <form class="form-horizontal" method="post" action="<?php echo $this->url(); ?>" enctype="multipart/form-data">
        
        <div class="form-group">
          <label for="textArea" class="col-lg-2 control-label">Intoduction * </label>
          <div class="col-lg-8">
              <textarea class="form-control" rows="3" name="intro" required="true"></textarea>
            <span class="help-block">Give an intro to your Product.</span>
          </div>
        </div>
        
        <div class="form-group">
          <label for="textArea" class="col-lg-2 control-label">Details * </label>
          <div class="col-lg-8">
              <textarea class="form-control" rows="5" name="detail" required="true"></textarea>
            <span class="help-block"></span>
          </div>
        </div>
    <br>
    
    <div class="">
          <label for="textArea" class="col-lg-2 control-label">Add one or more Media </label>
          <div class="col-lg-8">
              <div id="filediv"><input name="file[]" type="file" id="file"/></div><br/>
              <input type="button" id="add_more" class="btn btn-warning" value="Add More Files"/>
            <span class="help-block"> Only JPEG,PNG,JPG, MP4, MKV, 3GP Type Image Uploaded. Image Size Should Be Less Than 5MB.</span>
          </div>
        </div>
       
       
       <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-default">Cancel</button>
      </div>
    </div>
      
    </div>
        
    </form>
    
</div>