<div class="container">
    <?php if(isset($this->message)) :?>
    <div class="alert alert-dismissible alert-success">

    <?php echo $this->message ;?>

    </div>    
 <?php endif;?>
<div class="container">
<!--<h3><?php echo "The User Name is ".$this->id?></h2>-->

<a href="<?php echo $this->url(
    array(
        'controller' => 'dashboard',
        'action'     => 'products'
    ),
    null,
        true); ?>"" class="btn btn-primary pull-right">Add Product Details</a>
</div>
    <br><br>
    <div class="container">
            <table class="table table-striped table-hover ">
            <thead>
              <tr>
                <th width="100">Sr No</th>
                <th>Product's Name</th>
                <th width='400'>Action</th>
              </tr>
            </thead>
            <?php if( count($this->display)): ?>
            <?php $i=1;?>
            <?php foreach ($this->display as $value): ?>
            <tbody>
                    <tr>
                      <td><?= $i; ?></td>
                      <td> <?php echo $value['intro']; ?></td> 
                      <td><a href="<?php echo $this->url(array(
                          'controller'     =>  'dashboard',
                          'action'         =>  'update'
                      ),NULL,TRUE)."?id=".$value['id'] ?>" class="btn btn-primary">Update</a> <a href="<?php echo $this->url(array(
                          'controller' => 'dashboard',
                          'action'     => 'delete'
                      ),NULL,true
                              )."?id=".$value['id']; ?>" class="btn btn-danger">Delete</a></td>   
                    </tr>
              <?php $i++; endforeach;?>
              <?php else: ?>
              <tr>
                  <td colspan="3"> No Record Found </td>
              </tr>
              <?php   endif;?>
            </tbody>
            </table> 
</div>