
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?php echo $this->layout()->title; ?></title>
        <?php echo $this->headLink()->appendStylesheet('/css/bootstrap.min.css') ?>
    </head>
    <body>
        <?php $this->session = new Zend_Session_Namespace('user_session');
          $this->session1 = new Zend_Session_Namespace('enduser_session');
          //echo $this->session->id;
          ?>
        <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
         <?php  if(!isset($this->session1->id)):?>
      <a class="navbar-brand" href="<?php echo $this->url(
    array(
        'controller' => 'Index',
    ),
    null,
        true); ?>">MyFollow</a>
        <?php else:?>
        <a class="navbar-brand" href="<?php echo $this->url(
    array(
        'controller' => 'home',
        'action'     => 'index'
    ),
    null,
        true); ?>">Home</a>
        <ul class="nav navbar-nav"><li ><a class="" href="<?php echo $this->url(
    array(
        'controller' => 'home',
        'action'     => 'products'
    ),
    null,
                true); ?>">Products</a></li></ul>
        <?php endif; ?>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav navbar-right">
          
        <?php  if(!isset($this->session->id) && !isset($this->session1->id)): ?>  
        <li><a href="<?php echo $this->url(
    array(
        'controller' => 'Index',
        'action'     => 'login'
    ),
    null,
        true); ?>">Login</a></li>
          <?php else:?>
          <li><a href="<?php echo $this->url(
    array(
        'controller' => 'index',
        'action'     => 'logout'
    ),
    null,
        true); ?>">Logout</a></li>
        <?php endif; ?>
      </ul> 
    </div>
  </div>
</nav>
<?php echo $this->layout()->content;  ?>

</body>
</html>