
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?php echo $this->layout()->title; ?></title>
        <?php echo $this->headLink()->appendStylesheet('/css/bootstrap.min.css') ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<?php echo $this->url(
    array(
        'controller' => 'Index',
    ),
    null,
        true); ?>">MyFollow</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav navbar-right">
          <?php $this->session = new Zend_Session_Namespace('user_session');
          //echo $this->session->id;
          ?>
        <?php  if(!isset($this->session->id)): ?>  
        <li><a href="<?php echo $this->url(
    array(
        'controller' => 'Index',
        'action'     => 'login'
    ),
    null,
        true); ?>">Login</a></li>
          <?php else:?>
          <li><a href="<?php echo $this->url(
    array(
        'controller' => 'index',
        'action'     => 'logout'
    ),
    null,
        true); ?>">Logout</a></li>
        <?php endif; ?>
      </ul> 
    </div>
  </div>
</nav>
<?php echo $this->layout()->content;  ?>

</body>
</html>