<div class="container">
    <?php if(isset($this->message)) :?>
    <div class="alert alert-dismissible alert-success">

    <?php echo $this->message ;?>

    </div>    
 <?php endif;?>
<form class="form-horizontal" action="<?php echo $this->url(
    array(
        'controller' => 'Admin',
        'action'     => 'add'
    ),
    null,
        true); ?>" method="post" >
  <fieldset>
    <legend>Apply for the Registration</legend>
    <div class="form-group">
            <label for="inputName" class="col-lg-2 control-label">Name</label>
            <div class="col-lg-5">
                <input type="text" class="form-control"  required="true" id="name" name="name" placeholder="Name">
            </div>
          </div>
    <div class="form-group">
            <label for="inputEmail" class="col-lg-2 control-label">Email</label>
            <div class="col-lg-5">
                <input type="text" class="form-control" required="true" id="email" name="email" placeholder="Email">
            </div>
    </div>
    <div class="form-group">
            <label for="companyname" class="col-lg-2 control-label">Company Name</label>
            <div class="col-lg-5">
                <input type="text" class="form-control" required="true" name="companyName" placeholder="Company Name">
            </div>
    </div>
    <div class="form-group">
            <div class="col-lg-5 col-lg-offset-2">
              <button type="reset" class="btn btn-default">Cancel</button>
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
    </div>
  </fieldset>
</form>
</div>

  
<h1> Welcome to add </h1>
