
<form class="form-horizontal" action="<?php echo $this->url(
    array(
        'controller' => 'Admin',
        'action'     => 'add'
    ),
    null,
        true); ?>" method="post" >
  <fieldset>
    <legend>Product Owner Registration</legend>
    <div class="form-group">
      <label for="inputName" class="col-lg-2 control-label">Name</label>
      <div class="col-lg-5">
          <input type="text" class="form-control"  required="true" id="name" name="name" placeholder="Name">
      </div>
    </div>
    <div class="form-group">
      <label for="inputEmail" class="col-lg-2 control-label">Email</label>
      <div class="col-lg-5">
          <input type="text" class="form-control" required="true" id="email" name="email" placeholder="Email">
      </div>
    </div>
    <div class="form-group">
      <label for="companyname" class="col-lg-2 control-label">Company Name</label>
      <div class="col-lg-5">
          <input type="text" class="form-control" required="true" name="companyName" placeholder="Company Name">
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-5 col-lg-offset-2">
        <button type="reset" class="btn btn-default">Cancel</button>
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </fieldset>
</form>


  
