<script   src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $('.btn-primary').mouseover(function(){
       $(this).addClass('btn-success').text('approve');
    });
    $('.btn-primary').mouseout(function(){
       $(this).removeClass('btn-success').addClass('btn-primary').text('approve');
    });
    });
    
    </script>

<div class="container">
    
    <br><br>
   
     <table class="table table-striped table-hover ">
            <thead>
              <tr>
                <th width="100">Sr No</th>
                <th width="300">Email</th>
                <th>Company Name</th>
                <th width='300'>Action</th>
              </tr>
            </thead>
            <?php if( count($this->display)): ?>
             <?php $i=1;?>
            <?php foreach ($this->display as $value): ?>
            <tbody>
                    <tr>
                      <td><?= $i; ?></td>
                      <td> <?= $value['email']; ?></td>
                      <td> <?= $value['companyName']; ?></td>
                      <td> <?php if($value['approve'] == 0): ?><a href="<?php echo $this->url(array(
                          'controller' => 'admin',
                          'action'     => 'add'
                      ),NULL,true
                              )."?id=".$value['id']; ?>" class="btn btn-primary" id="approve">Approve</a> 
                      <?php else: ?>
                          <a class="btn btn-success" >Approved</a> 
                          <?php endif;?>
                      </td>
                    </tr>
                      <?php $i++;  endforeach;  ?>
              <?php else: ?>
              <tr>
                  <td colspan="3"> No Record Found </td>
              </tr>
              <?php   endif;?>
            </tbody>
            </table> 
</div>

