<br><br>
  
<div class="container">
    
<?php if(isset($this->message)) :?>
    <div class="alert alert-dismissible alert-success">

    <?php echo $this->message ;?>

    </div>    
 <?php endif;?>
    <table class="table table-striped table-hover ">
            <thead>
              <tr>
                <!--<th width="150">Sr No</th>
                <th>Product</th>-->
              </tr>
            </thead>
            <?php if( count($this->result)): ?>
            <?php foreach ($this->result as $value): ?>
            <tbody>
                <tr>
                    <!--<td><div class="jumbotron"><h4><?php echo $i; ?></h4></div></td>-->
                    <td>
                        <div class="jumbotron" >
                              <div class="lead"> <h4><?php echo $value['intro']; ?></h4> </div>
   
                              <a href="<?= $this->url(array(
                                  'controller'      => 'home',
                                  'action'          => 'unfollow'
                                  ),NULL,TRUE)."?productId=".$value['id']; ?>" class="btn btn-danger  pull-right"  >unfollow</a><br>
                                  
                        <?php $image = $this->images;
                            echo $image['productId'];
                        ?>
                                 
                <?php foreach ($this->images as $imagee): ?>
                    <?php if($value['id'] == $imagee['productId'] ):  ?>
                     <img alt="image" src="<?php echo $this->baseurl('/uploads/'.$imagee['image']); ?>" height="150" width="150" style="margin: 10" />
                 <?php endif;?>
                
                 <?php $i++; endforeach;?>
     
                          <br><br><br><br>
                <p class="lead"> <?= $value['detail']; ?></p>
                        </div>
                    </td>
                </tr>
            <?php $i++; endforeach;?>
                
            <?php endif;?>
                
           </tbody>
    </table>
</div>