<br><br>
  
<div class="container">
    
<?php if(isset($this->message)) :?>
    <div class="alert alert-dismissible alert-success">

    <?php echo $this->message ;?>

    </div>    
 <?php endif;?>
    <table class="table table-striped table-hover ">
            <thead>
              <tr>
                
              </tr>
            </thead>
            <?php if( count($this->result)): ?>
            <?php foreach ($this->result as $value): ?>
            <tbody>
                <tr>
                   <td>
                    <div class="jumbotron" >
                            <div class="lead"> <h4><?php echo nl2br($value['intro']); ?></h4> </div>
   
                             <a href="<?= $this->url(array(
                                  'controller'      => 'home',
                                  'action'          => 'linkedinunfollow'
                                  ),NULL,TRUE)."?productId=".$value['id']; ?>" class="btn btn-danger  pull-right"  >unfollow</a><br>
                      
                                  
                      <?php foreach ($this->images as $imagee): ?>
                            <?php if($value['id'] == $imagee['productId'] ):  ?>
                                  <a href="<?php echo $this->baseurl('/uploads/'.$imagee['image']); ?>" ><img alt="image" src="<?php echo $this->baseurl('/uploads/'.$imagee['image']); ?>" height="150" width="150" style="margin: 10; cursor:zoom-in  " /></a>
                            <?php endif;?>
                      <?php $i++; endforeach;?>
                            
                            
                          <br><br><br><br>
                    <p class="lead"> <?= nl2br($value['detail']); ?></p>
                    </div>
                  </td>
                </tr>
            <?php $i++; endforeach;?>
            <?php endif;?>
        </tbody>
   </table>
</div>