<?php $value = $this->result;?>
<?php $result = $this->companydetail;?>
<div class="container">
    <br><br>
    
            <div  class="col-lg-12" >
                <h3><?=  $value[0]['intro'];?></h3><br>
                <a href="<?php echo $this->url(['controller' => 'home',
                    'action'     => 'index'
                    ],NULL,true); ?>" class="btn btn-success btn-lg">Follow</a><a href="#abc" class="btn btn-warning  pull-right">View Company Profile</a><br><br><br>
                <?php if(!empty($value[0]['image1']) || !empty($value[0]['image2']) || !empty($value[0]['image3']) || !empty($value[0]['image4']) || !empty($value['image5'])): ?>
                     
                <img alt="image" src="<?php echo $this->baseurl('/uploads/'.$value[0]['image1']); ?>" height="150" width="150" style="margin: 10" />
                          <img alt="image" src="<?php echo $this->baseurl('/uploads/'.$value[0]['image2']); ?>" height="150" width="150" style="margin: 10;cursor: zoom-in"/>
                          <img alt="image" src="<?php echo $this->baseurl('/uploads/'.$value[0]['image3']); ?>" height="150" width="150" style="margin: 10;"/>
                          <img alt="image" src="<?php echo $this->baseurl('/uploads/'.$value[0]['image4']); ?>" height="150" width="150" style="margin: 10"/>
                          <img alt="image" src="<?php echo $this->baseurl('/uploads/'.$value[0]['image5']); ?>" height="150" width="150" style="margin: 10"/>
                         <?php endif;?>
                          <br><br><br><br>
                <p class="lead"> <?= $value[0]['detail']; ?></p>
            </div>
    <div > &nbsp&nbsp;<legend> <h5 id="abc">Company Details :</h5> </legend> 
        <h3> <?= $result[0]['companyName']; ?> </h3><br>
        <div class="lead"><?= $result[0]['description'];?></div> <br>
        <h5>Contact Details :</h5>
        <div class="lead"><?= $result[0]['street1'].",";?><br>
            <?= $result[0]['street2'].",";?><br>
            <?= $result[0]['city']." - ";?><?= $result[0]['pin'];?><br>
            <?= $result[0]['state']." - ";?><?= $result[0]['country'].".";?><br>
            <?= $result[0]['contactNo'];?><br>
            <?= $result[0]['websiteUrl'];?><br>
            <?= $result[0]['twitterHandler'];?><br>
            <?= $result[0]['facebookPage'];?><br>
        </div>    
        </div>
        <br><br>
        
        
        
</div>