

<html>
<head>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script>
//$(function(){
//
//        
//        $('.following').mouseover(function(){
//                  $(this).removeClass('following').addClass('unfollow').text("Unfollow");
//       });        
//        
//       $('.following').mouseout(function(){
//            $(this).removeClass('unfollow').text("follow");
//        }); 
//       
//	 $('.btn').click(function() {
//                 var element = $(this);
//		var productid = element.attr("id");
//                $(this).addClass('btn-success').text("Following");
//                 if(productid !== '')
//                 {
//                     $.post("follow",{'productid' : productid},
//                      
//                      function(respond){
//                          console.log(respond,"hello");
//                      }
//            );
//                 }
////
//            if($(this).hasClass('btn-success'))
//            {
//                $('.btn-success').mouseover(function(){
//                  $(this).addClass('btn-danger').text("Unfollow");
//                    });
//            }
//            if($(this).hasClass('btn-success'))
//            {
//                $('.btn-success').mouseout(function(){
//                  $(this).removeClass('btn-danger').addClass('btn-success').text("Following");
//                });
//            }
//            
           
            
//            var dataString = "productid="+productid;
//            $.ajax({  
//                    type: "POST",  
//                    url: "follow",  
//                    data: dataString,
//                    dataType : 'json',  
//                    success: function()
//                    {   
//                         $("#fadeo").delay(3000).fadeOut();
//                    }
//                });
//
//                    });  
//});
</script>
</head>
<body>

<br><br>
<div class="container">
    
       <?php if(isset($this->message)) :?>
    <div class="alert alert-dismissible alert-success">

    <?php echo $this->message ;?>

    </div>    
 <?php endif;?>
    <?php ($this->result); ?>
    <br>
    <table class="table table-striped table-hover ">
            <thead>
              <tr>
                <!--<th width="150">Sr No</th>
                <th>Product</th>-->
              </tr>
            </thead>
            <?php if( count($this->result)): ?>
            <?php foreach ($this->result as $value): ?>
            <tbody>
                <tr>
                    <!--<td><div class="jumbotron"><h4><?php echo $i; ?></h4></div></td>-->
                    <td>
                        <div class="jumbotron" >
                              <div class="lead"> <h4><?php echo $value['intro']; ?></h4> </div>
   
                              <a href="<?= $this->url(array(
                                  'controller'      => 'home',
                                  'action'          => 'follow'
                                  ),NULL,TRUE)."?productId=".$value['id']; ?>" class="btn btn-primary"  >Follow</a>
                        </div>
                    </td>
                </tr>
            <?php $i++; endforeach;?>
                
            <?php endif;?>
                
           </tbody>
    </table>
</div>
</body></html>